Updated worflow
updated

diff --git a/.github/workflow/workflow1.yml b/.github/workflow/workflow1.yml
--- a/.github/workflow/workflow1.yml
+++ b/.github/workflow/workflow1.yml
@@ -1,12 +1,12 @@
 name: CI Pipeline (DOC1)
 
 on:
+
 #Manually trigger workflow runs
 workflow_dispatch:
 #Trigger the workflow on push from the master/main branch
 push:
 branches: [ master]
-
 jobs:
 # Build job
 build:
@@ -17,5 +17,8 @@ runs-on: ubuntu-latest
 steps:
 # Check-out your repository
 - uses: actions/checkout@v3
+
+- name: To Show Error
+run: echo "Should fail at this point ..." ; exit 1
 - name: Run a one-line script
 run: echo "Continuous Integration"
